/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/basic/button/')['AButton']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ApiSelect: typeof import('./../src/components/core/schema-form/src/components/ApiSelect.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BasicArrow: typeof import('./../src/components/basic/basic-arrow/index.vue')['default']
    BasicHelp: typeof import('./../src/components/basic/basic-help/index.vue')['default']
    Button: typeof import('./../src/components/basic/button/button.vue')['default']
    CheckBox: typeof import('./../src/components/basic/check-box/index.vue')['default']
    ColumnSetting: typeof import('./../src/components/core/dynamic-table/src/components/table-settings/column-setting.vue')['default']
    ContextMenu: typeof import('./../src/components/basic/context-menu/src/ContextMenu.vue')['default']
    DraggableModal: typeof import('./../src/components/core/draggable-modal/index.vue')['default']
    DynamicTable: typeof import('./../src/components/core/dynamic-table/src/dynamic-table.vue')['default']
    EditableCell: typeof import('./../src/components/core/dynamic-table/src/components/editable-cell/index.vue')['default']
    FormAction: typeof import('./../src/components/core/schema-form/src/components/form-action.vue')['default']
    HuaweiCharge: typeof import('./../src/components/basic/lockscreen/huawei-charge.vue')['default']
    IconsSelect: typeof import('./../src/components/basic/icons-select/index.vue')['default']
    IframePage: typeof import('./../src/components/basic/iframe-page/index.vue')['default']
    ImportExcel: typeof import('./../src/components/basic/excel/src/ImportExcel.vue')['default']
    LocalePicker: typeof import('./../src/components/basic/locale-picker/index.vue')['default']
    Lockscreen: typeof import('./../src/components/basic/lockscreen/index.vue')['default']
    LockscreenPage: typeof import('./../src/components/basic/lockscreen/lockscreen-page.vue')['default']
    ProConfigProvider: typeof import('./../src/components/basic/pro-config-provider/index.vue')['default']
    Progress: typeof import('./../src/components/basic/progress/index.vue')['default']
    RefreshSetting: typeof import('./../src/components/core/dynamic-table/src/components/table-settings/refresh-setting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./../src/components/core/schema-form/src/schema-form.vue')['default']
    SchemaFormItem: typeof import('./../src/components/core/schema-form/src/schema-form-item.vue')['default']
    SizeSetting: typeof import('./../src/components/core/dynamic-table/src/components/table-settings/size-setting.vue')['default']
    SplitPanel: typeof import('./../src/components/basic/split-panel/index.vue')['default']
    SvgIcon: typeof import('./../src/components/basic/svg-icon/svg-icon.vue')['default']
    TableAction: typeof import('./../src/components/core/dynamic-table/src/components/table-action.vue')['default']
    TableSettings: typeof import('./../src/components/core/dynamic-table/src/components/table-settings/index.vue')['default']
    TitleI18n: typeof import('./../src/components/basic/title-i18n/index.vue')['default']
    ToolBar: typeof import('./../src/components/core/dynamic-table/src/components/tool-bar/index.vue')['default']
    XiaomiCharge: typeof import('./../src/components/basic/lockscreen/xiaomi-charge.vue')['default']
  }
}
